sources:
    - Mekorot-Rashi-Bold_Italic.ufo
    - Mekorot-Rashi-Bold.ufo
    - Mekorot-Rashi-Bold.ufo
    - Mekorot-Rashi-Bold.ufo
    - Mekorot-Vilna-Bold-Italic.ufo
    - Mekorot-Vilna-Bold.ufo
    - Mekorot-Vilna-Italic.ufo
    - Mekorot-Vilna.ufo
